**Np.Sort**

In [44]:
#np.sort
import numpy as np
a = np.random.randint(1,100,15)
a


array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [45]:
np.sort(a)

array([ 3,  5, 11, 13, 16, 25, 29, 54, 58, 59, 63, 67, 68, 75, 82],
      dtype=int32)

In [46]:
#now 2d array sorting
b= np.random.randint(1,100,24).reshape(6,4)
b

array([[56,  7, 57, 26],
       [61, 18, 23,  9],
       [68, 10, 32,  2],
       [59,  3, 57, 81],
       [43,  8, 24, 55],
       [83, 72, 83,  7]], dtype=int32)

In [47]:
np.sort(b)

array([[ 7, 26, 56, 57],
       [ 9, 18, 23, 61],
       [ 2, 10, 32, 68],
       [ 3, 57, 59, 81],
       [ 8, 24, 43, 55],
       [ 7, 72, 83, 83]], dtype=int32)

In [48]:
#for sorting in rows 
np.sort(b,axis=0)

array([[43,  3, 23,  2],
       [56,  7, 24,  7],
       [59,  8, 32,  9],
       [61, 10, 57, 26],
       [68, 18, 57, 55],
       [83, 72, 83, 81]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [49]:
# code
np.append(a,200)

array([ 58,   3,  75,  13,  67,  63,  25,   5,  11,  54,  82,  59,  68,
        16,  29, 200])

In [50]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[56.        ,  7.        , 57.        , 26.        ,  0.96327378],
       [61.        , 18.        , 23.        ,  9.        ,  0.49863854],
       [68.        , 10.        , 32.        ,  2.        ,  0.80468679],
       [59.        ,  3.        , 57.        , 81.        ,  0.92207092],
       [43.        ,  8.        , 24.        , 55.        ,  0.84840363],
       [83.        , 72.        , 83.        ,  7.        ,  0.13670723]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [51]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [55]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [56]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [57]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [58]:
np.unique(e)


array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [59]:
    # code
a.shape

(15,)

In [60]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [61]:
np.expand_dims(a,axis=1)

array([[58],
       [ 3],
       [75],
       [13],
       [67],
       [63],
       [25],
       [ 5],
       [11],
       [54],
       [82],
       [59],
       [68],
       [16],
       [29]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [62]:
a


array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [63]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  4,  5,  9, 10, 11, 12]),)

In [65]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  3,  0, 13,  0,  0, 25,  5, 11,  0,  0,  0,  0, 16, 29],
      dtype=int32)

In [66]:
np.where(a%2 == 0,0,a)

array([ 0,  3, 75, 13, 67, 63, 25,  5, 11,  0,  0, 59,  0,  0, 29],
      dtype=int32)

In [68]:
a[np.where(a>50)]

array([58, 75, 67, 63, 54, 82, 59, 68], dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [69]:
# code
a


array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [ ]:
np.argmax(a) #answer will be in indices 

np.int64(10)

In [71]:
b

array([[56,  7, 57, 26],
       [61, 18, 23,  9],
       [68, 10, 32,  2],
       [59,  3, 57, 81],
       [43,  8, 24, 55],
       [83, 72, 83,  7]], dtype=int32)

In [72]:
np.argmax(b,axis=0)

array([5, 5, 5, 3])

In [73]:
np.argmax(b,axis=1)

array([2, 0, 0, 3, 3, 0])

In [74]:
# np.argmin
np.argmin(a)

np.int64(1)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [75]:
a

array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [76]:
np.cumsum(a)

array([ 58,  61, 136, 149, 216, 279, 304, 309, 320, 374, 456, 515, 583,
       599, 628])

In [77]:
b

array([[56,  7, 57, 26],
       [61, 18, 23,  9],
       [68, 10, 32,  2],
       [59,  3, 57, 81],
       [43,  8, 24, 55],
       [83, 72, 83,  7]], dtype=int32)

In [78]:
np.cumsum(b)

array([ 56,  63, 120, 146, 207, 225, 248, 257, 325, 335, 367, 369, 428,
       431, 488, 569, 612, 620, 644, 699, 782, 854, 937, 944])

In [79]:
np.cumsum(b, axis=1)

array([[ 56,  63, 120, 146],
       [ 61,  79, 102, 111],
       [ 68,  78, 110, 112],
       [ 59,  62, 119, 200],
       [ 43,  51,  75, 130],
       [ 83, 155, 238, 245]])

In [81]:
    # np.cumprod
np.cumprod(a)
#it multiplyies

array([                 58,                 174,               13050,
                    169650,            11366550,           716092650,
               17902316250,         89511581250,        984627393750,
            53169879262500,    4359930099525000,  257235875871975000,
       -954704514415251616, 3171471843065525760, -261036919647511040])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [82]:
a

array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [83]:
np.percentile(a,50)

np.float64(54.0)

In [84]:
np.median(a)

np.float64(54.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [85]:
# code
a

array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [86]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [87]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)


array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [89]:
# code
a

array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [90]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html|

In [91]:
# code
a

array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [92]:
np.flip(a)

array([29, 16, 68, 59, 82, 54, 11,  5, 25, 63, 67, 13, 75,  3, 58],
      dtype=int32)

In [93]:
b

array([[56,  7, 57, 26],
       [61, 18, 23,  9],
       [68, 10, 32,  2],
       [59,  3, 57, 81],
       [43,  8, 24, 55],
       [83, 72, 83,  7]], dtype=int32)

In [94]:
np.flip(b,axis=1)

array([[26, 57,  7, 56],
       [ 9, 23, 18, 61],
       [ 2, 32, 10, 68],
       [81, 57,  3, 59],
       [55, 24,  8, 43],
       [ 7, 83, 72, 83]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [95]:
a

array([58,  3, 75, 13, 67, 63, 25,  5, 11, 54, 82, 59, 68, 16, 29],
      dtype=int32)

In [96]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [97]:
a

array([110, 530,  75,  13,  67,  63,  25,   5,  11,  54,  82,  59,  68,
        16,  29], dtype=int32)

In [98]:
np.delete(a,[0,2,4])

array([530,  13,  63,  25,   5,  11,  54,  82,  59,  68,  16,  29],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [100]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [101]:
np.intersect1d(m,n)

array([3, 4, 5])

In [102]:
np.setdiff1d(n,m)

array([6, 7])

In [103]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [107]:
np.in1d(m)

AttributeError: module 'numpy' has no attribute 'in1d'

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [108]:
a

array([110, 530,  75,  13,  67,  63,  25,   5,  11,  54,  82,  59,  68,
        16,  29], dtype=int32)

In [109]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 67, 63, 25, 25, 25, 54, 75, 59, 68, 25, 29],
      dtype=int32)