Numpy arrays vs Python List

In [1]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

2.5889956951141357


In [4]:
#numpy 
import numpy as np 
np.arange (10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start) #it take very less time to execute

0.7145431041717529


In [5]:
3.26/0.06

54.33333333333333

In [ ]:
# memory
a = [i for i in range (10000000)]
import sys
#library for system to know the size of this list in the memory

sys.getsizeof(a)

89095160

In [7]:
a = np.arange(10000000,dtype=np.int8)#as we can reduce size in np by using dtype
sys.getsizeof(a)

10000112

Advance indexing

In [8]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a[1,2]

np.int64(6)

In [11]:
a[1:3,1:3]


array([[ 5,  6],
       [ 9, 10]])

In [12]:
# Fancy Indexing

a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [13]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[33,  9, 35, 15],
       [84, 19, 59, 55],
       [87, 43, 74, 93],
       [24, 17, 93, 40],
       [45, 44, 46, 94],
       [41, 88, 37, 91]], dtype=int32)