Numpy Array

In [2]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(a)
#output is a vector

[1 2 3]


In [ ]:
#this is a 2D array
b = np.array([[1,2],[2,3]])
print(b)
#output is a matrix

[[1 2]
 [2 3]]


In [ ]:
#3D array
c= np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
print(c)
#output is a Tensor

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


In [11]:
#dtype
e = np.array([1,2,3],dtype=float)
print(e)
#here the datatype us changes as float it can be bool, int, string


[1. 2. 3.]


In [17]:
#np.arange

a =np.arange(1,10) #it gives numbers from 1 to 10

b =np.arange(1,10,2) #it gives numbers leaving every 2 space
print(a,b)


[1 2 3 4 5 6 7 8 9] [1 3 5 7 9]


In [ ]:
# np with reshape

np.arange(1,11).reshape(5,2)
#it will form a 5 rows and 2 column


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#np.ones and np.zeros
#this are use for initializing arrays  
#specially used in neural network and machine learning
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
#np.random

np.random.random((3,4))

array([[0.76251182, 0.85736961, 0.45380117, 0.40455386],
       [0.40192126, 0.55552992, 0.67737743, 0.57418792],
       [0.09878653, 0.26885016, 0.80191082, 0.69788203]])

In [ ]:
#np.linspace

np.linspace(1,10,5)

#first number(1)is starting point
#second number(10) is ending point
#third number (5) is point required on equal space


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#np.identity

np.identity(8)# here in identity only diagonals are 1 remaining are 0

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

Array Attributes

In [ ]:
a1 = np.arange(10) #1 dimension
a2 = np.arange(12,dtype=float).reshape(3,4) #2 dimension
a3 = np.arange(8).reshape(2,2,2) # 3 dimension


In [ ]:
#ndim (number of Dimensions)

a1.ndim

3

In [43]:
#shape 
print(a3.shape)
#use for knowing number of column and shapes

(2, 2, 2)


In [ ]:
#size
print(a2.size)
#number of items

12


In [45]:
# itemsize
a1.itemsize

8

In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing Datatype

In [54]:
#astype
#it is use to change the datatype to reduce the memory size of the datatype

a1.astype(np.int32)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Array operations

In [62]:
a1 = np.arange(12).reshape (3,4)
a2 = np.arange(12,24).reshape (3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#scalar operations
#arithmetic
a1+2  #we can try any arithmetic operations
    

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
#relational operators

a1>5
#it will give true or false


array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [65]:
# vector operations
#arithmetic

a1+a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array function

In [73]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)
a1

array([[56., 39., 56., 14.],
       [14., 18., 73., 41.],
       [83., 79., 13., 48.]])

In [ ]:
#max, min, sum, prod

np.max(a1)


83.0
13.0


In [ ]:
np.min(a1)

np.float64(13.0)

In [79]:
np.sum(a1)

np.float64(534.0)

In [ ]:
np.prod(a1,axis=0) #axis means which column 0 column and 1 is row

array([65072., 55458., 53144., 27552.])

In [82]:
 ## mean/median/std/var
np.var(a1,axis=1)

array([295.6875, 550.25  , 792.6875])

In [83]:
     # dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [84]:
# log and exponents
np.exp(a1)

array([[2.09165950e+24, 8.65934004e+16, 2.09165950e+24, 1.20260428e+06],
       [1.20260428e+06, 6.56599691e+07, 5.05239363e+31, 6.39843494e+17],
       [1.11286375e+36, 2.03828107e+34, 4.42413392e+05, 7.01673591e+20]])

In [85]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)


array([[56., 76., 24.],
       [96., 81., 79.]])

Indexing and Slicing

In [ ]:
import numpy as np
a1 = np.arange(12)
a2 = np.arange(12).reshape((3,4))
a3 = np.arange(8).reshape((2,2,2))


In [16]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a2[2,3]

np.int64(11)

In [20]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
a3[1,0,1]

np.int64(5)

In [22]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[2:5:2] #multiplication by 2

array([2, 4])