Numpy arrays vs Python List

In [1]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

3.3693788051605225


In [2]:
#numpy 
import numpy as np 
np.arange (10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start) #it take very less time to execute

0.7870907783508301


In [3]:
3.26/0.06

54.33333333333333

In [4]:
# memory
a = [i for i in range (10000000)]
import sys
#library for system to know the size of this list in the memory

sys.getsizeof(a)

89095160

In [5]:
a = np.arange(10000000,dtype=np.int8)#as we can reduce size in np by using dtype
sys.getsizeof(a)

10000112

Advance indexing

In [6]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a[1,2]

np.int64(6)

In [8]:
a[1:3,1:3]


array([[ 5,  6],
       [ 9, 10]])

In [9]:
# Fancy Indexing

a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [10]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[86, 36, 53, 19],
       [80,  1, 44,  1],
       [78, 18, 65, 16],
       [85, 35, 83, 10],
       [75, 42, 37, 97],
       [92, 50, 20, 44]], dtype=int32)

In [17]:
# Boolean Indexing
import time
b= time.time()
a = np.random.randint(1,100,24).reshape(6,4) #random integers

print (time.time()-b)

a

0.001001119613647461


array([[37, 57, 61, 30],
       [82, 71, 24, 44],
       [64, 96, 50, 15],
       [45, 38,  5, 25],
       [70, 91, 78, 46],
       [13, 88, 85,  8]], dtype=int32)

In [18]:
# find all numbers greater than 50
a[a > 50]

array([57, 61, 82, 71, 64, 96, 70, 91, 78, 88, 85], dtype=int32)

In [19]:
# find out even numbers
a[a % 2 == 0]

array([30, 82, 24, 44, 64, 96, 50, 38, 70, 78, 46, 88,  8], dtype=int32)

In [ ]:
# find all numbers greater than 50 and are even
#here we merge two  different logics

a[(a > 50) & (a % 2 == 0)]

array([82, 64, 96, 70, 78, 88], dtype=int32)

In [21]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([37, 57, 61, 30, 82, 71, 24, 44, 64, 96, 50, 15, 45, 38,  5, 25, 78,
       46, 13, 88, 85,  8], dtype=int32)

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.