Numpy Array

In [129]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(a)
#output is a vector

[1 2 3]


In [130]:
#this is a 2D array
b = np.array([[1,2],[2,3]])
print(b)
#output is a matrix

[[1 2]
 [2 3]]


In [131]:
#3D array
c= np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
print(c)
#output is a Tensor

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


In [132]:
#dtype
e = np.array([1,2,3],dtype=float)
print(e)
#here the datatype us changes as float it can be bool, int, string


[1. 2. 3.]


In [133]:
#np.arange

a =np.arange(1,10) #it gives numbers from 1 to 10

b =np.arange(1,10,2) #it gives numbers leaving every 2 space
print(a,b)


[1 2 3 4 5 6 7 8 9] [1 3 5 7 9]


In [134]:
# np with reshape

np.arange(1,11).reshape(5,2)
#it will form a 5 rows and 2 column


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [135]:
#np.ones and np.zeros
#this are use for initializing arrays  
#specially used in neural network and machine learning
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [136]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
#np.random

np.random.random((3,4))

array([[0.16809083, 0.33782462, 0.844218  , 0.79422574],
       [0.25050707, 0.72453551, 0.32688008, 0.3751265 ],
       [0.12311961, 0.44343768, 0.94873191, 0.42626221]])

In [138]:
#np.linspace

np.linspace(1,10,5)

#first number(1)is starting point
#second number(10) is ending point
#third number (5) is point required on equal space


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [139]:
#np.identity

np.identity(8)# here in identity only diagonals are 1 remaining are 0

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

Array Attributes

In [140]:
a1 = np.arange(10) #1 dimension
a2 = np.arange(12,dtype=float).reshape(3,4) #2 dimension
a3 = np.arange(8).reshape(2,2,2) # 3 dimension


In [141]:
#ndim (number of Dimensions)

a1.ndim

1

In [142]:
#shape 
print(a3.shape)
#use for knowing number of column and shapes

(2, 2, 2)


In [143]:
#size
print(a2.size)
#number of items

12


In [144]:
# itemsize
a1.itemsize

8

In [145]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing Datatype

In [146]:
#astype
#it is use to change the datatype to reduce the memory size of the datatype

a1.astype(np.int32)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Array operations

In [147]:
a1 = np.arange(12).reshape (3,4)
a2 = np.arange(12,24).reshape (3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
#scalar operations
#arithmetic
a1+2  #we can try any arithmetic operations
    

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [149]:
#relational operators

a1>5
#it will give true or false


array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [150]:
# vector operations
#arithmetic

a1+a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array function

In [151]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)
a1

array([[18.,  7., 76.,  4.],
       [20., 88., 90., 69.],
       [ 3., 15., 57., 24.]])

In [152]:
#max, min, sum, prod

np.max(a1)


np.float64(90.0)

In [153]:
np.min(a1)

np.float64(3.0)

In [154]:
np.sum(a1)

np.float64(471.0)

In [155]:
np.prod(a1,axis=0) #axis means which column 0 column and 1 is row

array([  1080.,   9240., 389880.,   6624.])

In [156]:
 ## mean/median/std/var
np.var(a1,axis=1)

array([852.1875, 795.6875, 402.1875])

In [157]:
     # dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [158]:
# log and exponents
np.exp(a1)

array([[6.56599691e+07, 1.09663316e+03, 1.01480039e+33, 5.45981500e+01],
       [4.85165195e+08, 1.65163625e+38, 1.22040329e+39, 9.25378173e+29],
       [2.00855369e+01, 3.26901737e+06, 5.68572000e+24, 2.64891221e+10]])

In [159]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)


array([[76., 83., 80.],
       [72., 51., 32.]])

Indexing and Slicing

In [160]:
import numpy as np
a1 = np.arange(12)
a2 = np.arange(12).reshape((3,4))
a3 = np.arange(8).reshape((2,2,2))


In [161]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
a2[2,3]

np.int64(11)

In [163]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [164]:
a3[1,0,1]

np.int64(5)

In [165]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [166]:
a1[2:5]

array([2, 3, 4])

In [167]:
a1[2:5:2] #multiplication by 2

array([2, 4])

In [168]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
a2[0,:] #its for displaying first row

array([0, 1, 2, 3])

In [170]:
a2[:,0]  #for displaying first row

array([0, 4, 8])

In [171]:
a2[0,1] #displaying specific number

np.int64(1)

In [172]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
a2[::2,1::2] #four corner number

array([[ 1,  3],
       [ 9, 11]])

In [174]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [175]:
a2[1,::3] 

array([4, 7])

In [176]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [177]:
a3 = np.arange(27).reshape((3,3,3))
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [178]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [179]:
a3[0,1]

array([3, 4, 5])

In [180]:
a3[1,:,1]

array([10, 13, 16])

In [181]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [182]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [183]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [187]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [188]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [185]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [190]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [191]:
for i in a3 :
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
    print(i)
    #converting 3d into 1d for print all the items one by one

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [193]:
#reshape

In [197]:
#Transpose
np.transpose(a2) 
#it changes column into rows & rows into column

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [199]:
#Ravel
#it convert ony Dimension array to 1D array
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [ ]:

a4 = np.arange(12).reshape((3,4))
a5 = np.arange(12,24).reshape(3,4)

In [205]:
#Horizontal Stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [207]:
#vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [208]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
# Horizontal splitting

np.hsplit(a2,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [213]:
#vertical splitting
np.vsplit(a2,3) #first five which array you have to split then in how many parts to split

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]